## Services
google_analytics:
duoshuo:

## Meta
rss: https://jysperm.me/atom.xml
favicon: /favicon.png
icon: /favicon.png
source_url:
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  '首页': /
  'Windows': /
  'Mac': /
  'Android': /
  'iOS': /

right_menus:
  # 'RSS': /atom.xml
  '机场推荐':
    target: '_blank'
    href: '/'

## Banners && Widgets
banners:
  # jade: |
  #   a(href='https://github.com/jysperm/hexo-theme-simpleblock') 与精子同款的博客主题 simpleblock 现已发布！

  jade: |
    ul
      li
        | 稳定高速老牌clash订阅推荐 
        a(href='https://a.aiguobit.com' target='_blank') 倚天剑clash
        | 多年机场技术沉淀值得信赖！

widgets:
  -
    markdown: |
      Clash是目前最流行用户体验最好的网络代理工具，支持自动切换路线、按规则分流等功能，
      完美满足大部分网友的外网上网需求。

      支持的协议：

      * shadowsocks(R)
      * VMESS
      * VLESS
      * Trojan
      * Hysteria(2)
      * TUIC
      * WireGuard

  -
    tags: true

  -
    archives: true

  -
    copyright: true

## SNS (Work in progress)
sns:
  qq: '184300584'
  qun: '61137226'
  v2ex: 'jybox'
  mobile: '17091927884'
  github: 'jysperm'
  keybase: 'jysperm'
  zhihu: 'jysperm'
  google_plus: '+王子亭jysperm'
  segmentfault: 'jysperm'
  twitter: 'jysperm'
  bitcoin: '13v2BTCMZMHg5v87susgg86HFZqXERuwUd'
